### ISSUE TITLE
Bug with the dirt dropping code

### ISSUE THREAD

**Issue by blayzenw** [BuddaT/WGenerator#11]
When trying to find a place to drop the dirt it was looking at the tiles below with an x
x--x--o
x--x--o
o--o--o

It should be all of them like this
x--x--x
x--x--x
x--x--x

Its just the exit condition on the for loops, it should be i >= x and j >= y instead of i > x and j > y

This is what the function should be (starting at WGenerator line 336)

private Point findDropTile(int x, int y, double maxSlope, double maxDiagSlope) {
ArrayList<Point> slopes = new ArrayList<Point>();
double currentHeight = getTileHeight(x, y);

for (int i = x + 1; i >= x - 1; i--) {
for (int j = y + 1; j >= y - 1; j--) {
if (i < 0 || j < 0 || i >= heightMap.getMapSize() || j >= heightMap.getMapSize())
continue;

.
.
.

**Comment by BuddaT** [comment]
Ah shit, good catch. Fixed.

I was wondering why some tiles were getting a high slope of dirt instead of sliding, this explains it.
