### ISSUE TITLE
Dropping dirt causes a level-slope perimeter around the mountain line

### ISSUE THREAD

**Issue by TatharNuar** [BuddaT/WGenerator#4]
The drop dirt step of the map generator currently causes a level-slope perimeter around the mountain line, as dropped dirt reaches the max dirt height.  

This can be resolved by having the "dirt per tile" parameter taper off near the max dirt height, rather than stop abruptly.  I also propose adding an additional parameter to determine where the "dirt per tile" parameter starts to taper off, to complement the "max dirt height" parameter.

**Comment by BuddaT** [comment]
This should be fixed in the latest version.
